CREATE TABLE callback_requests (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	phone VARCHAR(50) NOT NULL,
	page VARCHAR(255) DEFAULT NULL,
	mail_sent TINYINT(1) NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE contact_requests (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) DEFAULT NULL,
	email VARCHAR(150) NOT NULL,
	subject VARCHAR(150) DEFAULT NULL,
	message TEXT NOT NULL,
	mail_sent TINYINT(1) NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE quick_contact_requests (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(150) NOT NULL,
	page VARCHAR(255) DEFAULT NULL,
	mail_sent TINYINT(1) NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;